#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/sql/parser.racc".
#

require 'racc/parser'


require File.dirname(__FILE__) + '/parser.rex.rb'


module SQL

  class Parser < Racc::Parser

module_eval <<'..end lib/sql/parser.racc modeval..id7500c84128', 'lib/sql/parser.racc', 247

def self.parse(sql)
  new.scan_str(sql)
end
..end lib/sql/parser.racc modeval..id7500c84128

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 52, :_reduce_none,
 3, 54, :_reduce_2,
 3, 53, :_reduce_3,
 2, 53, :_reduce_4,
 1, 55, :_reduce_5,
 1, 55, :_reduce_6,
 3, 57, :_reduce_7,
 1, 57, :_reduce_none,
 3, 58, :_reduce_9,
 1, 58, :_reduce_none,
 4, 56, :_reduce_11,
 2, 61, :_reduce_12,
 1, 65, :_reduce_none,
 1, 65, :_reduce_none,
 1, 68, :_reduce_none,
 1, 67, :_reduce_none,
 1, 67, :_reduce_none,
 3, 69, :_reduce_18,
 4, 69, :_reduce_19,
 5, 70, :_reduce_20,
 1, 71, :_reduce_21,
 2, 71, :_reduce_22,
 1, 71, :_reduce_23,
 2, 71, :_reduce_24,
 1, 71, :_reduce_25,
 1, 71, :_reduce_26,
 2, 71, :_reduce_27,
 1, 72, :_reduce_none,
 1, 72, :_reduce_none,
 2, 73, :_reduce_30,
 4, 74, :_reduce_31,
 1, 76, :_reduce_none,
 0, 62, :_reduce_none,
 2, 62, :_reduce_34,
 0, 63, :_reduce_none,
 3, 63, :_reduce_36,
 3, 78, :_reduce_37,
 1, 78, :_reduce_none,
 1, 79, :_reduce_none,
 0, 64, :_reduce_none,
 2, 64, :_reduce_41,
 6, 81, :_reduce_42,
 5, 81, :_reduce_43,
 4, 83, :_reduce_44,
 3, 83, :_reduce_45,
 3, 84, :_reduce_46,
 3, 85, :_reduce_47,
 1, 85, :_reduce_none,
 4, 86, :_reduce_49,
 3, 86, :_reduce_50,
 4, 87, :_reduce_51,
 3, 87, :_reduce_52,
 2, 88, :_reduce_53,
 1, 66, :_reduce_54,
 3, 77, :_reduce_55,
 1, 77, :_reduce_none,
 1, 75, :_reduce_none,
 3, 75, :_reduce_58,
 1, 89, :_reduce_none,
 3, 89, :_reduce_60,
 2, 90, :_reduce_61,
 1, 90, :_reduce_none,
 1, 91, :_reduce_none,
 1, 92, :_reduce_none,
 3, 92, :_reduce_65,
 1, 93, :_reduce_none,
 1, 93, :_reduce_none,
 1, 93, :_reduce_none,
 1, 93, :_reduce_none,
 1, 93, :_reduce_none,
 1, 93, :_reduce_none,
 3, 94, :_reduce_72,
 3, 94, :_reduce_73,
 3, 94, :_reduce_74,
 3, 94, :_reduce_75,
 3, 94, :_reduce_76,
 3, 94, :_reduce_77,
 1, 82, :_reduce_none,
 1, 95, :_reduce_none,
 1, 59, :_reduce_none,
 3, 96, :_reduce_81,
 3, 96, :_reduce_82,
 1, 96, :_reduce_none,
 3, 97, :_reduce_84,
 3, 97, :_reduce_85,
 1, 97, :_reduce_none,
 2, 98, :_reduce_87,
 2, 98, :_reduce_88,
 1, 98, :_reduce_none,
 1, 99, :_reduce_none,
 1, 99, :_reduce_none,
 1, 99, :_reduce_none,
 3, 99, :_reduce_93,
 1, 100, :_reduce_none,
 1, 100, :_reduce_none,
 3, 80, :_reduce_96,
 1, 80, :_reduce_none,
 1, 104, :_reduce_none,
 4, 101, :_reduce_99,
 1, 101, :_reduce_none,
 4, 105, :_reduce_101,
 4, 105, :_reduce_102,
 4, 105, :_reduce_103,
 4, 105, :_reduce_104,
 4, 105, :_reduce_105,
 1, 60, :_reduce_106,
 1, 103, :_reduce_107,
 1, 103, :_reduce_none,
 1, 106, :_reduce_none,
 2, 107, :_reduce_110,
 1, 102, :_reduce_none,
 3, 108, :_reduce_112,
 2, 108, :_reduce_113,
 2, 108, :_reduce_114,
 1, 108, :_reduce_115 ]

racc_reduce_n = 116

racc_shift_n = 200

racc_action_table = [
    11,   147,   111,    24,    68,   112,   115,   106,   107,   116,
   108,   109,   123,   125,    58,   128,   130,   131,   149,    11,
   150,   151,   132,   122,   124,   126,   127,   129,    32,   136,
    55,    56,   117,   113,   119,   104,    23,    27,    11,    29,
    34,    36,     4,     8,    10,    14,    18,    32,    25,    59,
    85,   160,   134,   136,   137,    23,    27,   161,    29,    34,
    36,     4,     8,    10,    14,    18,    32,    25,    89,   139,
   140,   141,   142,   143,    23,    27,    68,    29,    34,    36,
     4,     8,    10,    14,    18,   145,    25,    11,    87,    77,
    72,    75,    75,    72,    68,   100,    32,    62,    60,    57,
   156,    54,   -54,    53,    23,    27,    51,    29,    34,    36,
     4,     8,    10,    14,    18,    32,    25,    89,     1,    49,
    32,    48,   114,    23,    27,    68,    29,    34,    36,     4,
     8,    10,    14,    18,    47,    25,    11,   156,    46,   174,
    44,   177,   178,   119,   100,    32,   179,   136,    43,   185,
    42,   187,   188,    23,    27,    11,    29,    34,    36,     4,
     8,    10,    14,    18,    32,    25,    32,    39,   191,    38,
     1,   136,    23,    27,    11,    29,    34,    36,     4,     8,
    10,    14,    18,    32,    25,    75,   197,   198,    75,   nil,
   nil,    23,    27,    11,    29,    34,    36,     4,     8,    10,
    14,    18,    32,    25,   nil,   nil,   nil,   nil,   nil,   nil,
    23,    27,   nil,    29,    34,    36,     4,     8,    10,    14,
    18,    32,    25,    89,   nil,   nil,   nil,   nil,   nil,    23,
    27,   nil,    29,    34,    36,     4,     8,    10,    14,    18,
   nil,    25,   nil,    87,   nil,   nil,   nil,   nil,   nil,   nil,
   100,    32,    89,   nil,   nil,   nil,   nil,   nil,   nil,    23,
    27,   nil,    29,    34,    36,     4,     8,    10,    14,    18,
   nil,    25,    87,    11,   nil,   nil,   nil,   nil,   nil,   100,
    32,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    23,    27,
   nil,    29,    34,    36,     4,     8,    10,    14,    18,    11,
    25,    32,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    11,
   nil,   nil,    29,    34,    36,     4,     8,    10,    14,    18,
   111,    25,   nil,   112,   nil,   106,   107,    32,   108,   109,
   180,   181,   nil,   nil,   nil,    23,    27,    32,    29,    34,
    36,     4,     8,    10,    14,    18,    89,    25,    29,    34,
    36,     4,     8,    10,    14,    18,   nil,    25,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    11,    87,   nil,   nil,   nil,
   nil,   nil,   nil,   100,    32,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    23,    27,    11,    29,    34,    36,     4,     8,
    10,    14,    18,    32,    25,   nil,   nil,   nil,   nil,   nil,
   nil,    23,    27,   nil,    29,    34,    36,     4,     8,    10,
    14,    18,    32,    25,    89,   nil,   nil,   nil,   nil,   nil,
    23,    27,   nil,    29,    34,    36,     4,     8,    10,    14,
    18,   nil,    25,    11,    87,   nil,   nil,   nil,   nil,   nil,
   nil,   100,    32,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    23,    27,    11,    29,    34,    36,     4,     8,    10,    14,
    18,    32,    25,   nil,   nil,   nil,   nil,   nil,   nil,    23,
    27,    11,    29,    34,    36,     4,     8,    10,    14,    18,
    32,    25,   nil,   nil,   nil,   nil,   nil,   nil,    23,    27,
    11,    29,    34,    36,     4,     8,    10,    14,    18,    32,
    25,   nil,   nil,   nil,   nil,   nil,   nil,    23,    27,    11,
    29,    34,    36,     4,     8,    10,    14,    18,    32,    25,
   nil,   nil,   nil,   nil,   nil,   nil,    23,    27,    11,    29,
    34,    36,     4,     8,    10,    14,    18,    32,    25,   nil,
   nil,   nil,   nil,   nil,   nil,    23,    27,    11,    29,    34,
    36,     4,     8,    10,    14,    18,    32,    25,   nil,   nil,
   nil,   nil,   nil,   nil,    23,    27,    11,    29,    34,    36,
     4,     8,    10,    14,    18,    32,    25,   nil,   nil,   nil,
   nil,   nil,   nil,    23,    27,    11,    29,    34,    36,     4,
     8,    10,    14,    18,    32,    25,   nil,   nil,   nil,   nil,
   nil,   nil,    23,    27,    11,    29,    34,    36,     4,     8,
    10,    14,    18,    32,    25,   nil,   nil,   nil,   nil,   nil,
   nil,    23,    27,    11,    29,    34,    36,     4,     8,    10,
    14,    18,    32,    25,   nil,   nil,   nil,   nil,   nil,   nil,
    23,    27,    11,    29,    34,    36,     4,     8,    10,    14,
    18,    32,    25,   nil,   nil,   nil,   nil,   nil,   nil,    23,
    27,   nil,    29,    34,    36,     4,     8,    10,    14,    18,
    32,    25,    89,   nil,   nil,   nil,   nil,   nil,    23,    27,
   nil,    29,    34,    36,     4,     8,    10,    14,    18,   nil,
    25,    11,    87,   nil,    79,   nil,   nil,   nil,   nil,   100,
    32,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    23,    27,
    11,    29,    34,    36,     4,     8,    10,    14,    18,    32,
    25,   nil,   nil,   nil,   nil,   nil,   nil,    23,    27,    11,
    29,    34,    36,     4,     8,    10,    14,    18,    32,    25,
   nil,   nil,   nil,   nil,   nil,   nil,    23,    27,   nil,    29,
    34,    36,     4,     8,    10,    14,    18,    32,    25,   nil,
   nil,   nil,   nil,   nil,   nil,    23,    27,   nil,    29,    34,
    36,     4,     8,    10,    14,    18,   nil,    25 ]

racc_action_check = [
     1,   121,    69,     1,   143,    69,    78,    69,    69,    79,
    69,    69,    96,    96,    37,    96,    96,    96,   123,   187,
   123,   123,    96,    96,    96,    96,    96,    96,     1,   121,
    35,    35,    82,    70,    88,    63,     1,     1,   185,     1,
     1,     1,     1,     1,     1,     1,     1,   187,     1,    37,
    61,   131,   100,   102,   104,   187,   187,   131,   187,   187,
   187,   187,   187,   187,   187,   187,   185,   187,   180,   105,
   107,   108,   109,   110,   185,   185,   111,   185,   185,   185,
   185,   185,   185,   185,   185,   112,   185,   174,   180,    51,
   120,    49,    48,    45,    42,   180,   180,    41,    38,    36,
   128,    34,    32,    29,   180,   180,    25,   180,   180,   180,
   180,   180,   180,   180,   180,   174,   180,    87,   134,    22,
   137,    20,    71,   174,   174,   145,   174,   174,   174,   174,
   174,   174,   174,   174,    18,   174,   156,   150,    17,   153,
    10,   160,   163,   164,    87,    87,   165,   168,     8,   171,
     7,   175,   176,    87,    87,    11,    87,    87,    87,    87,
    87,    87,    87,    87,   156,    87,   179,     4,   181,     2,
     0,   190,   156,   156,   151,   156,   156,   156,   156,   156,
   156,   156,   156,    11,   156,   191,   194,   196,   197,   nil,
   nil,    11,    11,   149,    11,    11,    11,    11,    11,    11,
    11,    11,   151,    11,   nil,   nil,   nil,   nil,   nil,   nil,
   151,   151,   nil,   151,   151,   151,   151,   151,   151,   151,
   151,   149,   151,   139,   nil,   nil,   nil,   nil,   nil,   149,
   149,   nil,   149,   149,   149,   149,   149,   149,   149,   149,
   nil,   149,   nil,   139,   nil,   nil,   nil,   nil,   nil,   nil,
   139,   139,   136,   nil,   nil,   nil,   nil,   nil,   nil,   139,
   139,   nil,   139,   139,   139,   139,   139,   139,   139,   139,
   nil,   139,   136,    23,   nil,   nil,   nil,   nil,   nil,   136,
   136,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   136,   136,
   nil,   136,   136,   136,   136,   136,   136,   136,   136,   132,
   136,    23,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    27,
   nil,   nil,    23,    23,    23,    23,    23,    23,    23,    23,
   169,    23,   nil,   169,   nil,   169,   169,   132,   169,   169,
   169,   169,   nil,   nil,   nil,   132,   132,    27,   132,   132,
   132,   132,   132,   132,   132,   132,    89,   132,    27,    27,
    27,    27,    27,    27,    27,    27,   nil,    27,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   130,    89,   nil,   nil,   nil,
   nil,   nil,   nil,    89,    89,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    89,    89,   129,    89,    89,    89,    89,    89,
    89,    89,    89,   130,    89,   nil,   nil,   nil,   nil,   nil,
   nil,   130,   130,   nil,   130,   130,   130,   130,   130,   130,
   130,   130,   129,   130,    62,   nil,   nil,   nil,   nil,   nil,
   129,   129,   nil,   129,   129,   129,   129,   129,   129,   129,
   129,   nil,   129,   127,    62,   nil,   nil,   nil,   nil,   nil,
   nil,    62,    62,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    62,    62,    59,    62,    62,    62,    62,    62,    62,    62,
    62,   127,    62,   nil,   nil,   nil,   nil,   nil,   nil,   127,
   127,    56,   127,   127,   127,   127,   127,   127,   127,   127,
    59,   127,   nil,   nil,   nil,   nil,   nil,   nil,    59,    59,
    39,    59,    59,    59,    59,    59,    59,    59,    59,    56,
    59,   nil,   nil,   nil,   nil,   nil,   nil,    56,    56,   125,
    56,    56,    56,    56,    56,    56,    56,    56,    39,    56,
   nil,   nil,   nil,   nil,   nil,   nil,    39,    39,   124,    39,
    39,    39,    39,    39,    39,    39,    39,   125,    39,   nil,
   nil,   nil,   nil,   nil,   nil,   125,   125,    43,   125,   125,
   125,   125,   125,   125,   125,   125,   124,   125,   nil,   nil,
   nil,   nil,   nil,   nil,   124,   124,    44,   124,   124,   124,
   124,   124,   124,   124,   124,    43,   124,   nil,   nil,   nil,
   nil,   nil,   nil,    43,    43,    58,    43,    43,    43,    43,
    43,    43,    43,    43,    44,    43,   nil,   nil,   nil,   nil,
   nil,   nil,    44,    44,    46,    44,    44,    44,    44,    44,
    44,    44,    44,    58,    44,   nil,   nil,   nil,   nil,   nil,
   nil,    58,    58,   122,    58,    58,    58,    58,    58,    58,
    58,    58,    46,    58,   nil,   nil,   nil,   nil,   nil,   nil,
    46,    46,    57,    46,    46,    46,    46,    46,    46,    46,
    46,   122,    46,   nil,   nil,   nil,   nil,   nil,   nil,   122,
   122,   nil,   122,   122,   122,   122,   122,   122,   122,   122,
    57,   122,   119,   nil,   nil,   nil,   nil,   nil,    57,    57,
   nil,    57,    57,    57,    57,    57,    57,    57,    57,   nil,
    57,    54,   119,   nil,    54,   nil,   nil,   nil,   nil,   119,
   119,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   119,   119,
    55,   119,   119,   119,   119,   119,   119,   119,   119,    54,
   119,   nil,   nil,   nil,   nil,   nil,   nil,    54,    54,   126,
    54,    54,    54,    54,    54,    54,    54,    54,    55,    54,
   nil,   nil,   nil,   nil,   nil,   nil,    55,    55,   nil,    55,
    55,    55,    55,    55,    55,    55,    55,   126,    55,   nil,
   nil,   nil,   nil,   nil,   nil,   126,   126,   nil,   126,   126,
   126,   126,   126,   126,   126,   126,   nil,   126 ]

racc_action_pointer = [
   166,    -2,   169,   nil,   165,   nil,   nil,   142,   146,   nil,
   138,   153,   nil,   nil,   nil,   nil,   nil,   132,    85,   nil,
   114,   nil,    78,   271,   nil,    65,   nil,   307,   nil,    53,
   nil,   nil,    61,   nil,    99,    -8,    97,     9,    98,   488,
   nil,    79,    64,   545,   564,    90,   602,   nil,    62,    61,
   nil,    39,   nil,   nil,   689,   708,   469,   640,   583,   450,
   nil,    47,   412,    16,   nil,   nil,   nil,   nil,   nil,    -4,
    30,   119,   nil,   nil,   nil,   nil,   nil,   nil,     3,     6,
   nil,   nil,    29,   nil,   nil,   nil,   nil,   115,    10,   344,
   nil,   nil,   nil,   nil,   nil,   nil,   -10,   nil,   nil,   nil,
    50,   nil,    22,   nil,    34,    48,   nil,    57,    58,    59,
    63,    46,    75,   nil,   nil,   nil,   nil,   nil,   nil,   670,
    87,    -2,   621,    -5,   526,   507,   727,   431,    98,   382,
   363,    29,   297,   nil,   114,   nil,   250,    90,   nil,   221,
   nil,   nil,   nil,   -26,   nil,    95,   nil,   nil,   nil,   191,
   135,   172,   nil,   115,   nil,   nil,   134,   nil,   nil,   nil,
   113,   nil,   nil,   139,   119,   140,   nil,   nil,   116,   314,
   nil,   125,   nil,   nil,    85,   145,   149,   nil,   nil,   136,
    66,   166,   nil,   nil,   nil,    36,   nil,    17,   nil,   nil,
   140,   155,   nil,   nil,   180,   nil,   184,   158,   nil,   nil ]

racc_action_default = [
  -116,  -116,  -116,    -1,  -116,   -98,   -89,    -4,  -116,   -90,
  -116,  -116,   -92,    -6,  -107,   -94,   -91,    -8,  -116,   -95,
   -10,   -97,  -116,  -116,    -5,  -115,  -100,  -116,  -108,  -116,
  -109,   -80,  -106,  -111,  -116,   -83,  -116,   -86,  -116,  -116,
    -3,   -33,  -116,  -116,  -116,  -116,  -116,  -110,  -116,  -116,
   -87,  -113,   -88,  -114,  -116,  -116,  -116,  -116,  -116,  -116,
   200,  -116,  -116,   -35,   -13,   -14,   -16,   -17,   -54,   -12,
  -116,  -116,   -93,    -7,    -9,  -106,   -96,  -112,  -116,  -116,
   -81,   -82,  -116,   -84,   -85,  -103,   -71,  -116,   -57,  -116,
   -59,   -62,   -79,   -67,   -63,   -64,  -116,   -68,   -66,   -78,
  -116,   -69,   -34,   -70,  -116,   -40,   -21,   -23,   -25,   -26,
  -116,  -116,  -116,  -104,  -105,  -101,   -99,  -102,   -61,  -116,
   -79,  -116,  -116,  -116,  -116,  -116,  -116,  -116,  -116,  -116,
  -116,  -116,  -116,   -53,  -116,   -15,  -116,  -116,   -11,  -116,
   -22,   -24,   -27,  -116,   -18,  -116,   -60,   -65,   -73,  -116,
  -116,  -116,   -74,  -116,   -75,   -76,  -116,   -45,   -77,   -50,
  -116,   -52,   -72,  -116,   -58,   -36,   -38,   -39,   -41,  -116,
   -19,  -116,   -44,   -49,  -116,   -48,  -116,   -51,    -2,  -116,
  -116,  -116,   -20,   -28,   -29,  -116,   -43,  -116,   -46,   -37,
   -30,  -116,   -42,   -47,   -32,   -56,  -116,  -116,   -31,   -55 ]

racc_goto_table = [
    20,    74,    76,     3,   102,    64,    69,    13,   166,   167,
    45,   157,   148,   176,   152,   153,   154,   155,   183,   158,
   159,    50,   162,    83,    84,    52,    80,    81,   182,   184,
   133,   121,   196,   172,   194,   165,   138,   105,    61,   171,
    63,   173,    70,    71,   193,    20,    41,    40,   164,   146,
   189,   167,    73,    78,   118,     7,    82,   135,     2,   nil,
   nil,   nil,   nil,   nil,   186,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   144,   192,   nil,   nil,   nil,   nil,
   nil,   168,   nil,   nil,   nil,   nil,   nil,   nil,   120,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    64,   169,   170,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   190,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   163,   nil,   nil,
   nil,   nil,   nil,   nil,   195,   nil,   nil,   nil,   nil,   nil,
   199,   nil,   nil,   nil,   nil,   175,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   175 ]

racc_goto_check = [
     8,     9,     9,     2,    24,    15,    14,     6,    28,    29,
     8,    33,    31,    34,    31,    31,    31,    31,    22,    31,
    31,    48,    31,    46,    46,    48,    45,    45,    21,    23,
    17,    24,    25,    33,    26,    27,    13,    12,     8,    31,
    11,    31,     8,     8,    34,     8,    10,     5,    38,    39,
    28,    29,     6,     8,    40,     4,     8,     3,     1,   nil,
   nil,   nil,   nil,   nil,    31,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    15,    31,   nil,   nil,   nil,   nil,
   nil,    24,   nil,   nil,   nil,   nil,   nil,   nil,     8,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    15,    14,    15,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    24,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,   nil,
   nil,   nil,   nil,   nil,     9,   nil,   nil,   nil,   nil,   nil,
     9,   nil,   nil,   nil,   nil,     8,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     8 ]

racc_goto_pointer = [
   nil,    58,     3,   -43,    54,    40,     6,   nil,    -1,   -47,
    39,    -1,   -26,   -69,   -36,   -37,   nil,   -70,   nil,   nil,
   nil,  -141,  -151,  -140,   -58,  -159,  -157,  -102,  -129,  -128,
   nil,  -110,   nil,  -117,  -143,   nil,   nil,   nil,   -88,   -70,
   -33,   nil,   nil,   nil,   nil,   -29,   -35,   nil,    -2,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    17,    92,    21,
   nil,   nil,   nil,   nil,   nil,     5,    65,   nil,    66,    67,
   110,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    16,
    93,    96,    97,   nil,   nil,   101,   103,    86,    88,    90,
    91,    94,    95,    98,    99,    31,    35,    37,     6,     9,
    12,    15,    19,    22,    26,    28,    30,    33 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :left_paren => 2,
 :right_paren => 3,
 :SELECT => 4,
 :asterisk => 5,
 :comma => 6,
 :AS => 7,
 :FROM => 8,
 :CROSS => 9,
 :JOIN => 10,
 :INNER => 11,
 :LEFT => 12,
 :OUTER => 13,
 :RIGHT => 14,
 :FULL => 15,
 :ON => 16,
 :USING => 17,
 :WHERE => 18,
 :GROUP => 19,
 :BY => 20,
 :HAVING => 21,
 :NOT => 22,
 :BETWEEN => 23,
 :AND => 24,
 :IN => 25,
 :LIKE => 26,
 :IS => 27,
 :NULL => 28,
 :EXISTS => 29,
 :identifier => 30,
 :OR => 31,
 :equals_operator => 32,
 :not_equals_operator => 33,
 :less_than_operator => 34,
 :greater_than_operator => 35,
 :less_than_or_equals_operator => 36,
 :greater_than_or_equals_operator => 37,
 :plus_sign => 38,
 :minus_sign => 39,
 :solidus => 40,
 :period => 41,
 :COUNT => 42,
 :AVG => 43,
 :MAX => 44,
 :MIN => 45,
 :SUM => 46,
 :character_string_literal => 47,
 :DATE => 48,
 :date_string => 49,
 :unsigned_integer => 50 }

racc_use_result_var = true

racc_nt_base = 51

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'left_paren',
'right_paren',
'SELECT',
'asterisk',
'comma',
'AS',
'FROM',
'CROSS',
'JOIN',
'INNER',
'LEFT',
'OUTER',
'RIGHT',
'FULL',
'ON',
'USING',
'WHERE',
'GROUP',
'BY',
'HAVING',
'NOT',
'BETWEEN',
'AND',
'IN',
'LIKE',
'IS',
'NULL',
'EXISTS',
'identifier',
'OR',
'equals_operator',
'not_equals_operator',
'less_than_operator',
'greater_than_operator',
'less_than_or_equals_operator',
'greater_than_or_equals_operator',
'plus_sign',
'minus_sign',
'solidus',
'period',
'COUNT',
'AVG',
'MAX',
'MIN',
'SUM',
'character_string_literal',
'DATE',
'date_string',
'unsigned_integer',
'$start',
'statement',
'query_specification',
'subquery',
'select_list',
'table_expression',
'select_sublist',
'derived_column',
'value_expression',
'column_name',
'from_clause',
'where_clause',
'group_by_clause',
'having_clause',
'table_reference',
'table_name',
'joined_table',
'table_subquery',
'cross_join',
'qualified_join',
'join_type',
'join_specification',
'join_condition',
'named_columns_join',
'search_condition',
'join_column_list',
'column_name_list',
'grouping_column_reference_list',
'grouping_column_reference',
'column_reference',
'between_predicate',
'row_value_constructor',
'in_predicate',
'in_predicate_value',
'in_value_list',
'like_predicate',
'null_predicate',
'exists_predicate',
'boolean_term',
'boolean_factor',
'boolean_test',
'boolean_primary',
'predicate',
'comparison_predicate',
'row_value_constructor_element',
'numeric_value_expression',
'term',
'factor',
'value_expression_primary',
'unsigned_literal',
'set_function_specification',
'unsigned_numeric_literal',
'general_literal',
'qualifier',
'general_set_function',
'datetime_literal',
'date_literal',
'exact_numeric_literal']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 9
  def _reduce_2( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 12
  def _reduce_3( val, _values, result )
 result = SQL::Statement::Select.new(val[1], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 13
  def _reduce_4( val, _values, result )
 result = SQL::Statement::Select.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 16
  def _reduce_5( val, _values, result )
 result = SQL::Statement::All.new
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 17
  def _reduce_6( val, _values, result )
 result = SQL::Statement::SelectList.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 20
  def _reduce_7( val, _values, result )
 result = Array(val[0]) + Array(val[2])
   result
  end
.,.,

 # reduce 8 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 24
  def _reduce_9( val, _values, result )
 result = SQL::Statement::As.new(val[0], val[2])
   result
  end
.,.,

 # reduce 10 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 28
  def _reduce_11( val, _values, result )
 result = SQL::Statement::TableExpression.new(val[0], val[1], val[2], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 31
  def _reduce_12( val, _values, result )
 result = SQL::Statement::FromClause.new(val[1])
   result
  end
.,.,

 # reduce 13 omitted

 # reduce 14 omitted

 # reduce 15 omitted

 # reduce 16 omitted

 # reduce 17 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 45
  def _reduce_18( val, _values, result )
 result = SQL::Statement::CrossJoin.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 46
  def _reduce_19( val, _values, result )
 result = SQL::Statement::CrossJoin.new(val[0], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 49
  def _reduce_20( val, _values, result )
 result = val[1].new(val[0], val[3], val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 52
  def _reduce_21( val, _values, result )
 result = SQL::Statement::InnerJoin
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 53
  def _reduce_22( val, _values, result )
 result = SQL::Statement::LeftOuterJoin
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 54
  def _reduce_23( val, _values, result )
 result = SQL::Statement::LeftJoin
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 55
  def _reduce_24( val, _values, result )
 result = SQL::Statement::RightOuterJoin
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 56
  def _reduce_25( val, _values, result )
 result = SQL::Statement::RightJoin
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 57
  def _reduce_26( val, _values, result )
 result = SQL::Statement::FullJoin
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 58
  def _reduce_27( val, _values, result )
 result = SQL::Statement::FullOuterJoin
   result
  end
.,.,

 # reduce 28 omitted

 # reduce 29 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 65
  def _reduce_30( val, _values, result )
 result = SQL::Statement::On.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 68
  def _reduce_31( val, _values, result )
 result = SQL::Statement::Using.new(val[2])
   result
  end
.,.,

 # reduce 32 omitted

 # reduce 33 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 75
  def _reduce_34( val, _values, result )
 result = SQL::Statement::WhereClause.new(val[1])
   result
  end
.,.,

 # reduce 35 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 79
  def _reduce_36( val, _values, result )
 result = SQL::Statement::GroupByClause.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 82
  def _reduce_37( val, _values, result )
 result = Array(val[0]) + Array(val[2])
   result
  end
.,.,

 # reduce 38 omitted

 # reduce 39 omitted

 # reduce 40 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 90
  def _reduce_41( val, _values, result )
 result = SQL::Statement::HavingClause.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 94
  def _reduce_42( val, _values, result )
 result = SQL::Statement::Not.new(SQL::Statement::Between.new(val[0], val[3], val[5]))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 95
  def _reduce_43( val, _values, result )
 result = SQL::Statement::Between.new(val[0], val[2], val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 98
  def _reduce_44( val, _values, result )
 result = SQL::Statement::Not.new(SQL::Statement::In.new(val[0], val[3]))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 99
  def _reduce_45( val, _values, result )
 result = SQL::Statement::In.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 102
  def _reduce_46( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 105
  def _reduce_47( val, _values, result )
 result = Array(val[0]) + Array(val[2])
   result
  end
.,.,

 # reduce 48 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 112
  def _reduce_49( val, _values, result )
 result = SQL::Statement::Not.new(SQL::Statement::Like.new(val[0], val[3]))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 113
  def _reduce_50( val, _values, result )
 result = SQL::Statement::Like.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 116
  def _reduce_51( val, _values, result )
 result = SQL::Statement::Not.new(SQL::Statement::Is.new(val[0], SQL::Statement::Null.new))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 117
  def _reduce_52( val, _values, result )
 result = SQL::Statement::Is.new(val[0], SQL::Statement::Null.new)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 120
  def _reduce_53( val, _values, result )
 result = SQL::Statement::Exists.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 124
  def _reduce_54( val, _values, result )
 result = SQL::Statement::Table.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 127
  def _reduce_55( val, _values, result )
 result = Array(val[0]) + Array(val[2])
   result
  end
.,.,

 # reduce 56 omitted

 # reduce 57 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 133
  def _reduce_58( val, _values, result )
 result = SQL::Statement::Or.new(val[0], val[2])
   result
  end
.,.,

 # reduce 59 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 137
  def _reduce_60( val, _values, result )
 result = SQL::Statement::And.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 140
  def _reduce_61( val, _values, result )
 result = SQL::Statement::Not.new(val[1])
   result
  end
.,.,

 # reduce 62 omitted

 # reduce 63 omitted

 # reduce 64 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 148
  def _reduce_65( val, _values, result )
 result = val[1]
   result
  end
.,.,

 # reduce 66 omitted

 # reduce 67 omitted

 # reduce 68 omitted

 # reduce 69 omitted

 # reduce 70 omitted

 # reduce 71 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 159
  def _reduce_72( val, _values, result )
 result = SQL::Statement::Equals.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 160
  def _reduce_73( val, _values, result )
 result = SQL::Statement::Not.new(SQL::Statement::Equals.new(val[0], val[2]))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 161
  def _reduce_74( val, _values, result )
 result = SQL::Statement::Less.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 162
  def _reduce_75( val, _values, result )
 result = SQL::Statement::Greater.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 163
  def _reduce_76( val, _values, result )
 result = SQL::Statement::LessOrEquals.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 164
  def _reduce_77( val, _values, result )
 result = SQL::Statement::GreaterOrEquals.new(val[0], val[2])
   result
  end
.,.,

 # reduce 78 omitted

 # reduce 79 omitted

 # reduce 80 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 176
  def _reduce_81( val, _values, result )
 result = SQL::Statement::Add.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 177
  def _reduce_82( val, _values, result )
 result = SQL::Statement::Subtract.new(val[0], val[2])
   result
  end
.,.,

 # reduce 83 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 181
  def _reduce_84( val, _values, result )
 result = SQL::Statement::Multiply.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 182
  def _reduce_85( val, _values, result )
 result = SQL::Statement::Divide.new(val[0], val[2])
   result
  end
.,.,

 # reduce 86 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 186
  def _reduce_87( val, _values, result )
 result = SQL::Statement::UnaryPlus.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 187
  def _reduce_88( val, _values, result )
 result = SQL::Statement::UnaryMinus.new(val[1])
   result
  end
.,.,

 # reduce 89 omitted

 # reduce 90 omitted

 # reduce 91 omitted

 # reduce 92 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 194
  def _reduce_93( val, _values, result )
 result = val[1]
   result
  end
.,.,

 # reduce 94 omitted

 # reduce 95 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 201
  def _reduce_96( val, _values, result )
 result = SQL::Statement::QualifiedColumn.new(val[0], val[2])
   result
  end
.,.,

 # reduce 97 omitted

 # reduce 98 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 208
  def _reduce_99( val, _values, result )
 result = SQL::Statement::Count.new(SQL::Statement::All.new)
   result
  end
.,.,

 # reduce 100 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 212
  def _reduce_101( val, _values, result )
 result = SQL::Statement::Count.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 213
  def _reduce_102( val, _values, result )
 result = SQL::Statement::Average.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 214
  def _reduce_103( val, _values, result )
 result = SQL::Statement::Maximum.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 215
  def _reduce_104( val, _values, result )
 result = SQL::Statement::Minimum.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 216
  def _reduce_105( val, _values, result )
 result = SQL::Statement::Sum.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 220
  def _reduce_106( val, _values, result )
 result = SQL::Statement::Column.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 224
  def _reduce_107( val, _values, result )
 result = SQL::Statement::String.new(val[0])
   result
  end
.,.,

 # reduce 108 omitted

 # reduce 109 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 231
  def _reduce_110( val, _values, result )
 result = SQL::Statement::Date.new(val[1])
   result
  end
.,.,

 # reduce 111 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 237
  def _reduce_112( val, _values, result )
 result = SQL::Statement::Float.new("#{val[0]}.#{val[2]}".to_f)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 238
  def _reduce_113( val, _values, result )
 result = SQL::Statement::Float.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 239
  def _reduce_114( val, _values, result )
 result = SQL::Statement::Float.new("0.#{val[1]}".to_f)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 240
  def _reduce_115( val, _values, result )
 result = SQL::Statement::Integer.new(val[0])
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

  end   # class Parser

end   # module SQL
