#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/sql/parser.racc".
#

require 'racc/parser'


require File.dirname(__FILE__) + '/parser.rex.rb'


module SQL

  class Parser < Racc::Parser

module_eval <<'..end lib/sql/parser.racc modeval..iddfa3ea94b0', 'lib/sql/parser.racc', 286

def self.parse(sql)
  new.scan_str(sql)
end
..end lib/sql/parser.racc modeval..iddfa3ea94b0

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 54, :_reduce_none,
 1, 55, :_reduce_none,
 2, 56, :_reduce_3,
 0, 58, :_reduce_none,
 3, 58, :_reduce_5,
 3, 59, :_reduce_6,
 1, 59, :_reduce_none,
 2, 60, :_reduce_none,
 1, 61, :_reduce_none,
 0, 62, :_reduce_none,
 3, 64, :_reduce_11,
 1, 57, :_reduce_none,
 3, 65, :_reduce_13,
 2, 65, :_reduce_14,
 1, 66, :_reduce_15,
 1, 66, :_reduce_16,
 3, 68, :_reduce_17,
 1, 68, :_reduce_none,
 3, 69, :_reduce_19,
 2, 69, :_reduce_20,
 1, 69, :_reduce_none,
 4, 67, :_reduce_22,
 2, 71, :_reduce_23,
 3, 75, :_reduce_24,
 2, 75, :_reduce_25,
 1, 75, :_reduce_none,
 1, 75, :_reduce_none,
 1, 78, :_reduce_none,
 1, 77, :_reduce_none,
 1, 77, :_reduce_none,
 3, 79, :_reduce_31,
 4, 79, :_reduce_32,
 5, 80, :_reduce_33,
 1, 81, :_reduce_34,
 2, 81, :_reduce_35,
 1, 81, :_reduce_36,
 2, 81, :_reduce_37,
 1, 81, :_reduce_38,
 1, 81, :_reduce_39,
 2, 81, :_reduce_40,
 1, 82, :_reduce_none,
 1, 82, :_reduce_none,
 2, 83, :_reduce_43,
 4, 84, :_reduce_44,
 1, 86, :_reduce_none,
 0, 72, :_reduce_none,
 2, 72, :_reduce_47,
 0, 73, :_reduce_none,
 3, 73, :_reduce_49,
 3, 88, :_reduce_50,
 1, 88, :_reduce_none,
 1, 89, :_reduce_none,
 0, 74, :_reduce_none,
 2, 74, :_reduce_54,
 1, 91, :_reduce_none,
 6, 92, :_reduce_56,
 5, 92, :_reduce_57,
 4, 94, :_reduce_58,
 3, 94, :_reduce_59,
 1, 95, :_reduce_none,
 3, 95, :_reduce_61,
 3, 96, :_reduce_62,
 1, 96, :_reduce_none,
 4, 97, :_reduce_64,
 3, 97, :_reduce_65,
 4, 98, :_reduce_66,
 3, 98, :_reduce_67,
 2, 99, :_reduce_68,
 1, 76, :_reduce_69,
 3, 87, :_reduce_70,
 1, 87, :_reduce_none,
 1, 85, :_reduce_none,
 3, 85, :_reduce_73,
 1, 100, :_reduce_none,
 3, 100, :_reduce_75,
 2, 101, :_reduce_76,
 1, 101, :_reduce_none,
 1, 102, :_reduce_none,
 1, 103, :_reduce_none,
 3, 103, :_reduce_80,
 1, 104, :_reduce_none,
 1, 104, :_reduce_none,
 1, 104, :_reduce_none,
 1, 104, :_reduce_none,
 1, 104, :_reduce_none,
 1, 104, :_reduce_none,
 3, 105, :_reduce_87,
 3, 105, :_reduce_88,
 3, 105, :_reduce_89,
 3, 105, :_reduce_90,
 3, 105, :_reduce_91,
 3, 105, :_reduce_92,
 1, 93, :_reduce_none,
 1, 93, :_reduce_none,
 1, 106, :_reduce_none,
 1, 70, :_reduce_none,
 3, 107, :_reduce_97,
 3, 107, :_reduce_98,
 1, 107, :_reduce_none,
 3, 108, :_reduce_100,
 3, 108, :_reduce_101,
 1, 108, :_reduce_none,
 2, 109, :_reduce_103,
 2, 109, :_reduce_104,
 1, 109, :_reduce_none,
 1, 110, :_reduce_none,
 1, 110, :_reduce_none,
 1, 110, :_reduce_none,
 3, 110, :_reduce_109,
 1, 111, :_reduce_none,
 1, 111, :_reduce_none,
 3, 90, :_reduce_112,
 1, 90, :_reduce_none,
 1, 115, :_reduce_none,
 4, 112, :_reduce_115,
 1, 112, :_reduce_none,
 4, 116, :_reduce_117,
 4, 116, :_reduce_118,
 4, 116, :_reduce_119,
 4, 116, :_reduce_120,
 4, 116, :_reduce_121,
 1, 63, :_reduce_122,
 3, 114, :_reduce_123,
 2, 114, :_reduce_124,
 1, 114, :_reduce_none,
 1, 117, :_reduce_none,
 2, 118, :_reduce_127,
 1, 113, :_reduce_none,
 3, 119, :_reduce_129,
 2, 119, :_reduce_130,
 2, 119, :_reduce_131,
 1, 119, :_reduce_132 ]

racc_reduce_n = 133

racc_shift_n = 224

racc_action_table = [
    25,   192,   132,    35,   189,     4,    57,   128,   101,   177,
   190,   178,   179,    69,   124,   133,   125,   126,    25,   129,
   130,   206,   208,   134,    56,   135,    39,   161,    56,    65,
    66,    53,    54,   136,    28,    30,   175,    36,    40,     9,
    12,    14,    18,    21,    39,    26,    68,    31,   137,    56,
   139,   141,    28,    30,    99,    36,    40,     9,    12,    14,
    18,    21,    39,    26,   115,    31,   143,    92,    91,   159,
    28,    30,   161,    36,    40,     9,    12,    14,    18,    21,
   162,    26,   105,    31,   175,   163,   164,    81,   166,   119,
    39,   167,    56,    56,    39,    56,    88,    81,    28,    30,
    77,    36,    40,     9,    12,    14,    18,    21,   115,    26,
    39,    31,    56,    70,    67,   -69,   185,    64,    28,    30,
    63,    36,    40,     9,    12,    14,    18,    21,    25,    26,
     4,    31,    60,   119,    39,   191,    91,    58,   103,    52,
    81,    81,    28,    30,   161,    36,    40,     9,    12,    14,
    18,    21,   175,    26,    39,    31,   196,    51,    50,   185,
    49,   200,    28,    30,    48,    36,    40,     9,    12,    14,
    18,    21,   175,    26,   203,    31,   143,    45,    39,    39,
   210,    44,   212,   213,    43,   215,    28,    30,     4,    36,
    40,     9,    12,    14,    18,    21,     7,    26,    39,    31,
    25,   161,     4,    56,   221,   222,    28,    30,    56,    36,
    40,     9,    12,    14,    18,    21,   nil,    26,   nil,    31,
   128,   nil,   nil,   nil,   nil,   nil,    39,   124,   115,   125,
   126,   nil,   129,   130,    28,    30,   nil,    36,    40,     9,
    12,    14,    18,    21,   nil,    26,   105,    31,    25,   nil,
   nil,   nil,   nil,   119,    39,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    28,    30,   nil,    36,    40,     9,    12,    14,
    18,    21,    25,    26,    39,    31,   nil,   nil,   nil,   nil,
   nil,   nil,    28,    30,   nil,    36,    40,     9,    12,    14,
    18,    21,   nil,    26,    25,    31,   nil,    96,    39,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    28,    30,   nil,    36,
    40,     9,    12,    14,    18,    21,    25,    26,   nil,    31,
    39,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,    30,
   nil,    36,    40,     9,    12,    14,    18,    21,    25,    26,
   nil,    31,    39,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    28,    30,   nil,    36,    40,     9,    12,    14,    18,    21,
    25,    26,   nil,    31,    39,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    28,    30,   nil,    36,    40,     9,    12,    14,
    18,    21,    25,    26,   nil,    31,    39,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    36,    40,     9,
    12,    14,    18,    21,   175,    26,   nil,    31,    39,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    36,
    40,     9,    12,    14,    18,    21,   175,    26,   nil,    31,
    39,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,    30,
   nil,    36,    40,     9,    12,    14,    18,    21,    25,    26,
   nil,    31,    39,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    28,    30,   nil,    36,    40,     9,    12,    14,    18,    21,
   175,    26,   nil,    31,    39,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    28,    30,   nil,    36,    40,     9,    12,    14,
    18,    21,   175,    26,   nil,    31,    39,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    28,    30,   nil,    36,    40,     9,
    12,    14,    18,    21,   nil,    26,   nil,    31,    39,   nil,
   115,   nil,   nil,   nil,   nil,   nil,    28,    30,   nil,    36,
    40,     9,    12,    14,    18,    21,   nil,    26,   105,    31,
   175,   nil,   nil,   nil,   nil,   119,    39,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    28,    30,   nil,    36,    40,     9,
    12,    14,    18,    21,   175,    26,    39,    31,   nil,   nil,
   nil,   nil,   nil,   nil,    28,    30,   nil,    36,    40,     9,
    12,    14,    18,    21,    25,    26,   nil,    31,   nil,   nil,
    39,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,    30,
   nil,    36,    40,     9,    12,    14,    18,    21,   nil,    26,
    39,    31,   115,   nil,     4,   nil,   nil,   nil,    28,    30,
   nil,    36,    40,     9,    12,    14,    18,    21,   nil,    26,
   105,    31,   175,   nil,   nil,   nil,   nil,   119,    39,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    28,    30,   nil,    36,
    40,     9,    12,    14,    18,    21,    25,    26,    39,    31,
   nil,   nil,   nil,   nil,   nil,   nil,    28,    30,   nil,    36,
    40,     9,    12,    14,    18,    21,    25,    26,   nil,    31,
   nil,   nil,    39,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    28,    30,   nil,    36,    40,     9,    12,    14,    18,    21,
    25,    26,    39,    31,   nil,   nil,   nil,   nil,   nil,   nil,
    28,    30,   nil,    36,    40,     9,    12,    14,    18,    21,
    25,    26,   nil,    31,   nil,   nil,    39,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    28,    30,   nil,    36,    40,     9,
    12,    14,    18,    21,   175,    26,    39,    31,   nil,   nil,
   nil,   nil,   nil,   nil,    28,    30,   nil,    36,    40,     9,
    12,    14,    18,    21,   nil,    26,   nil,    31,   nil,   nil,
    39,   nil,   115,   nil,   nil,   nil,   nil,   nil,    28,    30,
   nil,    36,    40,     9,    12,    14,    18,    21,   nil,    26,
   105,    31,   nil,   nil,   nil,   nil,   nil,   119,    39,   nil,
   115,   nil,   nil,   nil,   nil,   nil,    28,    30,   nil,    36,
    40,     9,    12,    14,    18,    21,   nil,    26,   105,    31,
   nil,   nil,   nil,   nil,   nil,   119,    39,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    28,    30,   nil,    36,    40,     9,
    12,    14,    18,    21,   nil,    26,   nil,    31,   146,   148,
   nil,   151,   153,   154,   nil,   nil,   nil,   nil,   144,   145,
   147,   149,   150,   152 ]

racc_action_check = [
     4,   157,    83,     4,   154,   159,    23,   195,    75,   146,
   154,   146,   146,    42,   195,    84,   195,   195,   212,   195,
   195,   195,   195,    85,    83,    86,     4,   157,    23,    38,
    38,    21,    21,    95,     4,     4,   210,     4,     4,     4,
     4,     4,     4,     4,   212,     4,    42,     4,    96,    99,
   102,   103,   212,   212,    71,   212,   212,   212,   212,   212,
   212,   212,   210,   212,   206,   212,   106,    63,    59,   119,
   210,   210,   120,   210,   210,   210,   210,   210,   210,   210,
   124,   210,   206,   210,   200,   126,   127,   128,   129,   206,
   206,   130,   132,    58,   141,    57,    54,    48,   206,   206,
    47,   206,   206,   206,   206,   206,   206,   206,   105,   206,
   200,   206,    44,    43,    40,    39,   151,    36,   200,   200,
    31,   200,   200,   200,   200,   200,   200,   200,   185,   200,
   185,   200,    26,   105,   105,   155,   156,    24,    76,    20,
   162,   164,   105,   105,   169,   105,   105,   105,   105,   105,
   105,   105,   179,   105,   185,   105,   170,    18,    14,   178,
    12,   181,   185,   185,    11,   185,   185,   185,   185,   185,
   185,   185,   177,   185,   189,   185,   193,     9,   179,   196,
   197,     7,   201,   202,     6,   208,   179,   179,     0,   179,
   179,   179,   179,   179,   179,   179,     3,   179,   177,   179,
   175,   214,   175,   215,   219,   220,   177,   177,   222,   177,
   177,   177,   177,   177,   177,   177,   nil,   177,   nil,   177,
    82,   nil,   nil,   nil,   nil,   nil,   175,    82,   161,    82,
    82,   nil,    82,    82,   175,   175,   nil,   175,   175,   175,
   175,   175,   175,   175,   nil,   175,   161,   175,    69,   nil,
   nil,   nil,   nil,   161,   161,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   161,   161,   nil,   161,   161,   161,   161,   161,
   161,   161,    68,   161,    69,   161,   nil,   nil,   nil,   nil,
   nil,   nil,    69,    69,   nil,    69,    69,    69,    69,    69,
    69,    69,   nil,    69,    67,    69,   nil,    67,    68,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    68,    68,   nil,    68,
    68,    68,    68,    68,    68,    68,    25,    68,   nil,    68,
    67,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    67,    67,
   nil,    67,    67,    67,    67,    67,    67,    67,    66,    67,
   nil,    67,    25,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    25,    25,   nil,    25,    25,    25,    25,    25,    25,    25,
    28,    25,   nil,    25,    66,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    66,    66,   nil,    66,    66,    66,    66,    66,
    66,    66,    30,    66,   nil,    66,    28,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,    28,    28,
    28,    28,    28,    28,   153,    28,   nil,    28,    30,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    30,
    30,    30,    30,    30,    30,    30,   152,    30,   nil,    30,
   153,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   153,   153,
   nil,   153,   153,   153,   153,   153,   153,   153,    65,   153,
   nil,   153,   152,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   152,   152,   nil,   152,   152,   152,   152,   152,   152,   152,
   150,   152,   nil,   152,    65,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    65,    65,   nil,    65,    65,    65,    65,    65,
    65,    65,   149,    65,   nil,    65,   150,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   150,   150,   nil,   150,   150,   150,
   150,   150,   150,   150,   nil,   150,   nil,   150,   149,   nil,
   139,   nil,   nil,   nil,   nil,   nil,   149,   149,   nil,   149,
   149,   149,   149,   149,   149,   149,   nil,   149,   139,   149,
   148,   nil,   nil,   nil,   nil,   139,   139,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   139,   139,   nil,   139,   139,   139,
   139,   139,   139,   139,   147,   139,   148,   139,   nil,   nil,
   nil,   nil,   nil,   nil,   148,   148,   nil,   148,   148,   148,
   148,   148,   148,   148,    45,   148,   nil,   148,   nil,   nil,
   147,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   147,   147,
   nil,   147,   147,   147,   147,   147,   147,   147,   nil,   147,
    45,   147,   115,   nil,   115,   nil,   nil,   nil,    45,    45,
   nil,    45,    45,    45,    45,    45,    45,    45,   nil,    45,
   115,    45,   145,   nil,   nil,   nil,   nil,   115,   115,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   115,   115,   nil,   115,
   115,   115,   115,   115,   115,   115,    49,   115,   145,   115,
   nil,   nil,   nil,   nil,   nil,   nil,   145,   145,   nil,   145,
   145,   145,   145,   145,   145,   145,    50,   145,   nil,   145,
   nil,   nil,    49,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    49,    49,   nil,    49,    49,    49,    49,    49,    49,    49,
    51,    49,    50,    49,   nil,   nil,   nil,   nil,   nil,   nil,
    50,    50,   nil,    50,    50,    50,    50,    50,    50,    50,
    52,    50,   nil,    50,   nil,   nil,    51,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    51,    51,   nil,    51,    51,    51,
    51,    51,    51,    51,   144,    51,    52,    51,   nil,   nil,
   nil,   nil,   nil,   nil,    52,    52,   nil,    52,    52,    52,
    52,    52,    52,    52,   nil,    52,   nil,    52,   nil,   nil,
   144,   nil,   143,   nil,   nil,   nil,   nil,   nil,   144,   144,
   nil,   144,   144,   144,   144,   144,   144,   144,   nil,   144,
   143,   144,   nil,   nil,   nil,   nil,   nil,   143,   143,   nil,
    77,   nil,   nil,   nil,   nil,   nil,   143,   143,   nil,   143,
   143,   143,   143,   143,   143,   143,   nil,   143,    77,   143,
   nil,   nil,   nil,   nil,   nil,    77,    77,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    77,    77,   nil,    77,    77,    77,
    77,    77,    77,    77,   nil,    77,   nil,    77,   114,   114,
   nil,   114,   114,   114,   nil,   nil,   nil,   nil,   114,   114,
   114,   114,   114,   114 ]

racc_action_pointer = [
   181,   nil,   nil,   194,    -5,   nil,   184,   178,   nil,   172,
   nil,   154,   155,   nil,   153,   nil,   nil,   nil,   152,   nil,
   135,   -17,   nil,    -3,    95,   311,    81,   nil,   355,   nil,
   377,    78,   nil,   nil,   nil,   nil,    65,   nil,   -10,    73,
   109,   nil,     5,   113,    81,   579,   nil,    80,    66,   651,
   671,   695,   715,   nil,    48,   nil,   nil,    64,    62,    62,
   nil,   nil,   nil,    15,   nil,   443,   333,   289,   267,   243,
   nil,    50,   nil,   nil,   nil,     2,   117,   795,   nil,   nil,
   nil,   nil,   216,    -7,     9,    17,    19,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    27,    42,   nil,   nil,    18,
   nil,   nil,    28,    48,   nil,   103,    41,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   825,   607,   nil,   nil,   nil,    64,
    40,   nil,   nil,   nil,    68,   nil,    70,    74,    56,    73,
    76,   nil,    61,   nil,   nil,   nil,   nil,   nil,   nil,   515,
   nil,    63,   nil,   767,   739,   627,   -15,   559,   535,   487,
   465,   111,   421,   399,   -19,   129,   130,    -5,   nil,    -2,
   nil,   223,   109,   nil,   110,   nil,   nil,   nil,   nil,   112,
   152,   nil,   nil,   nil,   nil,   195,   nil,   167,   154,   147,
   nil,   136,   nil,   nil,   nil,   123,   nil,   nil,   nil,   145,
   nil,   nil,   nil,   151,   nil,     3,   148,   155,   nil,   nil,
    79,   178,   177,   nil,   nil,   nil,    59,   nil,   180,   nil,
    31,   nil,    13,   nil,   169,   172,   nil,   nil,   nil,   198,
   201,   nil,   177,   nil ]

racc_action_default = [
  -133,    -1,    -2,    -4,  -133,   -12,  -133,  -133,    -3,  -133,
  -105,   -14,  -133,  -106,  -133,  -108,  -107,   -16,  -133,  -110,
   -18,  -133,  -111,   -21,  -133,  -133,  -133,  -116,  -133,  -125,
  -133,  -132,  -126,  -113,   -96,   -15,  -133,  -128,   -99,  -122,
  -133,  -114,  -102,  -133,  -133,  -133,   -13,   -46,  -133,  -133,
  -133,  -133,  -133,  -124,  -133,   -20,  -122,  -133,  -133,  -133,
  -127,  -103,  -104,  -130,  -131,  -133,  -133,  -133,  -133,  -133,
   224,    -5,    -7,   -10,    -9,  -133,   -48,  -133,   -27,   -29,
   -30,   -69,   -23,   -26,  -133,  -133,  -133,   -17,  -123,   -19,
  -112,  -109,  -129,   -97,   -98,  -133,  -133,  -101,  -100,  -133,
    -8,  -118,   -53,  -133,   -86,  -133,   -72,   -74,   -94,   -77,
   -95,   -82,   -78,   -79,  -133,  -133,   -83,   -81,   -93,  -133,
   -47,   -84,   -55,   -85,  -133,   -34,   -36,  -133,  -133,   -38,
   -39,   -25,  -133,  -119,  -120,  -121,  -117,  -115,    -6,  -133,
   -22,  -133,   -76,  -133,  -133,  -133,  -133,  -133,  -133,  -133,
  -133,  -133,  -133,  -133,  -133,  -133,   -95,  -133,   -68,  -133,
   -28,  -133,  -133,   -35,  -133,   -31,   -37,   -40,   -24,   -54,
   -49,   -51,   -52,   -75,   -87,  -133,   -88,  -133,  -133,  -133,
   -89,  -133,   -90,   -91,   -60,  -133,   -59,   -92,   -65,  -133,
   -67,   -11,   -80,   -73,   -32,  -133,  -133,  -133,   -58,   -64,
  -133,   -63,  -133,   -66,   -33,   -41,  -133,   -42,  -133,   -50,
  -133,   -57,  -133,   -61,   -43,  -133,   -56,   -62,   -71,  -133,
   -45,   -44,  -133,   -70 ]

racc_goto_table = [
    23,    55,   120,    82,    83,   171,    17,   160,   220,   174,
   176,   202,   180,   181,   182,   183,   172,   187,   188,    72,
   140,    59,    74,   186,    61,    46,    62,    93,    94,    97,
    98,    11,   158,   204,   205,    89,    90,   207,   217,   160,
   157,    75,   197,   100,   199,    84,    85,    86,    23,   219,
   198,   102,   170,    71,    87,     8,     3,     2,     1,   193,
   209,   131,   173,    95,   169,   211,   160,   142,    47,    76,
     6,   172,   nil,   nil,   138,   216,   nil,    74,   nil,   nil,
   nil,   nil,   nil,   nil,   165,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   168,   156,   nil,   nil,   nil,   nil,   nil,   nil,   194,   195,
    83,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   214,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    59,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   201,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   218,   nil,   nil,   nil,   nil,   nil,   nil,
   223,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   201 ]

racc_goto_check = [
    17,    10,    32,    22,    23,    36,    15,    11,    34,    40,
    40,    43,    40,    40,    40,    40,    37,    40,    40,     7,
    21,    17,    10,    42,    57,    14,    57,    54,    54,    55,
    55,    13,    25,    29,    30,    10,    10,    31,    43,    11,
    32,    17,    40,     9,    40,    17,    17,    17,    17,    33,
    42,    20,    35,     6,    15,     5,     4,     3,     2,    47,
    36,    10,    48,    17,    32,    40,    11,    49,    18,    19,
     1,    37,   nil,   nil,     7,    40,   nil,    10,   nil,   nil,
   nil,   nil,   nil,   nil,    23,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    10,    17,   nil,   nil,   nil,   nil,   nil,   nil,    23,    22,
    23,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    32,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    10,   nil,   nil,   nil,   nil,   nil,   nil,
    10,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    17 ]

racc_goto_pointer = [
   nil,    70,    58,    57,    56,    52,     9,   -25,   nil,   -30,
   -22,  -112,   nil,    27,    14,     2,   nil,    -4,    57,    22,
   -25,   -82,   -45,   -44,   nil,   -87,   nil,   nil,   nil,  -162,
  -161,  -158,   -75,  -166,  -207,   -89,  -136,  -125,   nil,   nil,
  -135,   nil,  -128,  -174,   nil,   nil,   nil,  -102,   -81,   -38,
   nil,   nil,   nil,   nil,   -38,   -39,   nil,    -4,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   155,   nil,   nil,   nil,    73,   nil,
    33,   122,     5,   nil,   nil,   nil,    20,   110,   nil,   nil,
   nil,   nil,   nil,    41,    78,   184,    79,    80,   127,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    16,   108,   111,
   114,   116,   nil,   nil,   121,   123,   104,   106,   107,   109,
   112,   113,   117,   118,    34,    38,    42,    10,    13,    15,
    19,    22,    24,    27,    29,    32,    37 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :ORDER => 2,
 :BY => 3,
 :comma => 4,
 :left_paren => 5,
 :right_paren => 6,
 :SELECT => 7,
 :asterisk => 8,
 :AS => 9,
 :FROM => 10,
 :CROSS => 11,
 :JOIN => 12,
 :INNER => 13,
 :LEFT => 14,
 :OUTER => 15,
 :RIGHT => 16,
 :FULL => 17,
 :ON => 18,
 :USING => 19,
 :WHERE => 20,
 :GROUP => 21,
 :HAVING => 22,
 :NOT => 23,
 :BETWEEN => 24,
 :AND => 25,
 :IN => 26,
 :LIKE => 27,
 :IS => 28,
 :NULL => 29,
 :EXISTS => 30,
 :identifier => 31,
 :OR => 32,
 :equals_operator => 33,
 :not_equals_operator => 34,
 :less_than_operator => 35,
 :greater_than_operator => 36,
 :less_than_or_equals_operator => 37,
 :greater_than_or_equals_operator => 38,
 :plus_sign => 39,
 :minus_sign => 40,
 :solidus => 41,
 :period => 42,
 :COUNT => 43,
 :AVG => 44,
 :MAX => 45,
 :MIN => 46,
 :SUM => 47,
 :quote => 48,
 :character_string_literal => 49,
 :DATE => 50,
 :date_string => 51,
 :unsigned_integer => 52 }

racc_use_result_var = true

racc_nt_base = 53

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'ORDER',
'BY',
'comma',
'left_paren',
'right_paren',
'SELECT',
'asterisk',
'AS',
'FROM',
'CROSS',
'JOIN',
'INNER',
'LEFT',
'OUTER',
'RIGHT',
'FULL',
'ON',
'USING',
'WHERE',
'GROUP',
'HAVING',
'NOT',
'BETWEEN',
'AND',
'IN',
'LIKE',
'IS',
'NULL',
'EXISTS',
'identifier',
'OR',
'equals_operator',
'not_equals_operator',
'less_than_operator',
'greater_than_operator',
'less_than_or_equals_operator',
'greater_than_or_equals_operator',
'plus_sign',
'minus_sign',
'solidus',
'period',
'COUNT',
'AVG',
'MAX',
'MIN',
'SUM',
'quote',
'character_string_literal',
'DATE',
'date_string',
'unsigned_integer',
'$start',
'direct_sql_statement',
'direct_sql_data_statement',
'direct_select_statement_multiple_rows',
'query_expression',
'order_by_clause',
'sort_specification_list',
'sort_specification',
'sort_key',
'ordering_specification',
'column_name',
'subquery',
'query_specification',
'select_list',
'table_expression',
'select_sublist',
'derived_column',
'value_expression',
'from_clause',
'where_clause',
'group_by_clause',
'having_clause',
'table_reference',
'table_name',
'joined_table',
'table_subquery',
'cross_join',
'qualified_join',
'join_type',
'join_specification',
'join_condition',
'named_columns_join',
'search_condition',
'join_column_list',
'column_name_list',
'grouping_column_reference_list',
'grouping_column_reference',
'column_reference',
'row_subquery',
'between_predicate',
'row_value_constructor',
'in_predicate',
'in_predicate_value',
'in_value_list',
'like_predicate',
'null_predicate',
'exists_predicate',
'boolean_term',
'boolean_factor',
'boolean_test',
'boolean_primary',
'predicate',
'comparison_predicate',
'row_value_constructor_element',
'numeric_value_expression',
'term',
'factor',
'value_expression_primary',
'unsigned_literal',
'set_function_specification',
'unsigned_numeric_literal',
'general_literal',
'qualifier',
'general_set_function',
'datetime_literal',
'date_literal',
'exact_numeric_literal']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

 # reduce 2 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 11
  def _reduce_3( val, _values, result )
 result = SQL::Statement::DirectSelect.new(val[0], val[1])
   result
  end
.,.,

 # reduce 4 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 16
  def _reduce_5( val, _values, result )
 result = SQL::Statement::OrderBy.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 19
  def _reduce_6( val, _values, result )
 result = Array(val[0]) + Array(val[2])
   result
  end
.,.,

 # reduce 7 omitted

 # reduce 8 omitted

 # reduce 9 omitted

 # reduce 10 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 36
  def _reduce_11( val, _values, result )
 result = SQL::Statement::Subquery.new(val[1])
   result
  end
.,.,

 # reduce 12 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 42
  def _reduce_13( val, _values, result )
 result = SQL::Statement::Select.new(val[1], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 43
  def _reduce_14( val, _values, result )
 result = SQL::Statement::Select.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 46
  def _reduce_15( val, _values, result )
 result = SQL::Statement::All.new
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 47
  def _reduce_16( val, _values, result )
 result = SQL::Statement::SelectList.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 50
  def _reduce_17( val, _values, result )
 result = Array(val[0]) + Array(val[2])
   result
  end
.,.,

 # reduce 18 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 54
  def _reduce_19( val, _values, result )
 result = SQL::Statement::As.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 55
  def _reduce_20( val, _values, result )
 result = SQL::Statement::As.new(val[0], val[1])
   result
  end
.,.,

 # reduce 21 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 59
  def _reduce_22( val, _values, result )
 result = SQL::Statement::TableExpression.new(val[0], val[1], val[2], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 62
  def _reduce_23( val, _values, result )
 result = SQL::Statement::FromClause.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 65
  def _reduce_24( val, _values, result )
 result = SQL::Statement::As.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 66
  def _reduce_25( val, _values, result )
 result = SQL::Statement::As.new(val[0], val[1])
   result
  end
.,.,

 # reduce 26 omitted

 # reduce 27 omitted

 # reduce 28 omitted

 # reduce 29 omitted

 # reduce 30 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 78
  def _reduce_31( val, _values, result )
 result = SQL::Statement::CrossJoin.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 79
  def _reduce_32( val, _values, result )
 result = SQL::Statement::CrossJoin.new(val[0], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 82
  def _reduce_33( val, _values, result )
 result = val[1].new(val[0], val[3], val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 85
  def _reduce_34( val, _values, result )
 result = SQL::Statement::InnerJoin
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 86
  def _reduce_35( val, _values, result )
 result = SQL::Statement::LeftOuterJoin
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 87
  def _reduce_36( val, _values, result )
 result = SQL::Statement::LeftJoin
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 88
  def _reduce_37( val, _values, result )
 result = SQL::Statement::RightOuterJoin
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 89
  def _reduce_38( val, _values, result )
 result = SQL::Statement::RightJoin
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 90
  def _reduce_39( val, _values, result )
 result = SQL::Statement::FullJoin
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 91
  def _reduce_40( val, _values, result )
 result = SQL::Statement::FullOuterJoin
   result
  end
.,.,

 # reduce 41 omitted

 # reduce 42 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 98
  def _reduce_43( val, _values, result )
 result = SQL::Statement::On.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 101
  def _reduce_44( val, _values, result )
 result = SQL::Statement::Using.new(val[2])
   result
  end
.,.,

 # reduce 45 omitted

 # reduce 46 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 108
  def _reduce_47( val, _values, result )
 result = SQL::Statement::WhereClause.new(val[1])
   result
  end
.,.,

 # reduce 48 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 112
  def _reduce_49( val, _values, result )
 result = SQL::Statement::GroupByClause.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 115
  def _reduce_50( val, _values, result )
 result = Array(val[0]) + Array(val[2])
   result
  end
.,.,

 # reduce 51 omitted

 # reduce 52 omitted

 # reduce 53 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 123
  def _reduce_54( val, _values, result )
 result = SQL::Statement::HavingClause.new(val[1])
   result
  end
.,.,

 # reduce 55 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 130
  def _reduce_56( val, _values, result )
 result = SQL::Statement::Not.new(SQL::Statement::Between.new(val[0], val[3], val[5]))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 131
  def _reduce_57( val, _values, result )
 result = SQL::Statement::Between.new(val[0], val[2], val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 134
  def _reduce_58( val, _values, result )
 result = SQL::Statement::Not.new(SQL::Statement::In.new(val[0], val[3]))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 135
  def _reduce_59( val, _values, result )
 result = SQL::Statement::In.new(val[0], val[2])
   result
  end
.,.,

 # reduce 60 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 139
  def _reduce_61( val, _values, result )
 result = SQL::Statement::InValueList.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 142
  def _reduce_62( val, _values, result )
 result = Array(val[0]) + Array(val[2])
   result
  end
.,.,

 # reduce 63 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 149
  def _reduce_64( val, _values, result )
 result = SQL::Statement::Not.new(SQL::Statement::Like.new(val[0], val[3]))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 150
  def _reduce_65( val, _values, result )
 result = SQL::Statement::Like.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 153
  def _reduce_66( val, _values, result )
 result = SQL::Statement::Not.new(SQL::Statement::Is.new(val[0], SQL::Statement::Null.new))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 154
  def _reduce_67( val, _values, result )
 result = SQL::Statement::Is.new(val[0], SQL::Statement::Null.new)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 157
  def _reduce_68( val, _values, result )
 result = SQL::Statement::Exists.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 161
  def _reduce_69( val, _values, result )
 result = SQL::Statement::Table.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 164
  def _reduce_70( val, _values, result )
 result = Array(val[0]) + Array(val[2])
   result
  end
.,.,

 # reduce 71 omitted

 # reduce 72 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 170
  def _reduce_73( val, _values, result )
 result = SQL::Statement::Or.new(val[0], val[2])
   result
  end
.,.,

 # reduce 74 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 174
  def _reduce_75( val, _values, result )
 result = SQL::Statement::And.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 177
  def _reduce_76( val, _values, result )
 result = SQL::Statement::Not.new(val[1])
   result
  end
.,.,

 # reduce 77 omitted

 # reduce 78 omitted

 # reduce 79 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 185
  def _reduce_80( val, _values, result )
 result = val[1]
   result
  end
.,.,

 # reduce 81 omitted

 # reduce 82 omitted

 # reduce 83 omitted

 # reduce 84 omitted

 # reduce 85 omitted

 # reduce 86 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 196
  def _reduce_87( val, _values, result )
 result = SQL::Statement::Equals.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 197
  def _reduce_88( val, _values, result )
 result = SQL::Statement::Not.new(SQL::Statement::Equals.new(val[0], val[2]))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 198
  def _reduce_89( val, _values, result )
 result = SQL::Statement::Less.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 199
  def _reduce_90( val, _values, result )
 result = SQL::Statement::Greater.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 200
  def _reduce_91( val, _values, result )
 result = SQL::Statement::LessOrEquals.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 201
  def _reduce_92( val, _values, result )
 result = SQL::Statement::GreaterOrEquals.new(val[0], val[2])
   result
  end
.,.,

 # reduce 93 omitted

 # reduce 94 omitted

 # reduce 95 omitted

 # reduce 96 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 214
  def _reduce_97( val, _values, result )
 result = SQL::Statement::Add.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 215
  def _reduce_98( val, _values, result )
 result = SQL::Statement::Subtract.new(val[0], val[2])
   result
  end
.,.,

 # reduce 99 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 219
  def _reduce_100( val, _values, result )
 result = SQL::Statement::Multiply.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 220
  def _reduce_101( val, _values, result )
 result = SQL::Statement::Divide.new(val[0], val[2])
   result
  end
.,.,

 # reduce 102 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 224
  def _reduce_103( val, _values, result )
 result = SQL::Statement::UnaryPlus.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 225
  def _reduce_104( val, _values, result )
 result = SQL::Statement::UnaryMinus.new(val[1])
   result
  end
.,.,

 # reduce 105 omitted

 # reduce 106 omitted

 # reduce 107 omitted

 # reduce 108 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 232
  def _reduce_109( val, _values, result )
 result = val[1]
   result
  end
.,.,

 # reduce 110 omitted

 # reduce 111 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 239
  def _reduce_112( val, _values, result )
 result = SQL::Statement::QualifiedColumn.new(val[0], val[2])
   result
  end
.,.,

 # reduce 113 omitted

 # reduce 114 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 246
  def _reduce_115( val, _values, result )
 result = SQL::Statement::Count.new(SQL::Statement::All.new)
   result
  end
.,.,

 # reduce 116 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 250
  def _reduce_117( val, _values, result )
 result = SQL::Statement::Count.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 251
  def _reduce_118( val, _values, result )
 result = SQL::Statement::Average.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 252
  def _reduce_119( val, _values, result )
 result = SQL::Statement::Maximum.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 253
  def _reduce_120( val, _values, result )
 result = SQL::Statement::Minimum.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 254
  def _reduce_121( val, _values, result )
 result = SQL::Statement::Sum.new(val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 258
  def _reduce_122( val, _values, result )
 result = SQL::Statement::Column.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 262
  def _reduce_123( val, _values, result )
 result = SQL::Statement::String.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 263
  def _reduce_124( val, _values, result )
 result = SQL::Statement::String.new('')
   result
  end
.,.,

 # reduce 125 omitted

 # reduce 126 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 270
  def _reduce_127( val, _values, result )
 result = SQL::Statement::Date.new(val[1])
   result
  end
.,.,

 # reduce 128 omitted

module_eval <<'.,.,', 'lib/sql/parser.racc', 276
  def _reduce_129( val, _values, result )
 result = SQL::Statement::Float.new("#{val[0]}.#{val[2]}".to_f)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 277
  def _reduce_130( val, _values, result )
 result = SQL::Statement::Float.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 278
  def _reduce_131( val, _values, result )
 result = SQL::Statement::Float.new("0.#{val[1]}".to_f)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/sql/parser.racc', 279
  def _reduce_132( val, _values, result )
 result = SQL::Statement::Integer.new(val[0])
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

  end   # class Parser

end   # module SQL
